# Generated by Django 2.1.7 on 2019-02-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrape',
            old_name='ndh_id',
            new_name='ndh_pk',
        ),
    ]
