# Generated by Django 2.1.7 on 2019-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190214_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productsndh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.BigIntegerField()),
                ('magento_id', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('special_from_date', models.CharField(blank=True, max_length=255, null=True)),
                ('special_to_date', models.CharField(blank=True, max_length=255, null=True)),
                ('msrp', models.FloatField()),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('is_in_stock', models.IntegerField()),
                ('min_qty', models.IntegerField(blank=True, null=True)),
                ('min_sale_qty', models.IntegerField(blank=True, null=True)),
                ('max_sale_qty', models.IntegerField(blank=True, null=True)),
                ('image_label', models.CharField(blank=True, max_length=255, null=True)),
                ('image_disabled', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('small_image', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('swatch_image', models.CharField(blank=True, max_length=255, null=True)),
                ('product_detail_attributes', models.TextField()),
                ('product_delivery_attributes', models.TextField()),
                ('product_images', models.TextField()),
                ('configurable_product_ids', models.TextField()),
                ('configurable_product_skus', models.TextField()),
                ('configurable_product_options', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category_magento_ids', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('ndh_promised', models.IntegerField(blank=True, null=True)),
                ('popular', models.IntegerField(blank=True, null=True)),
                ('trending', models.IntegerField(blank=True, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'productsndh',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
