# Generated by Django 2.1.7 on 2019-02-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190215_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='scrape_id',
        ),
        migrations.AddField(
            model_name='price',
            name='scrape_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Scrape'),
        ),
    ]
